INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Історія України / History of Ukraine',3);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Філософія / Philosophy',3);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Математичний аналіз / Mathematical Analysis',10);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Основи програмування / Fundamentals of Programming',7);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Лінійна алгебра і аналітична геометрія / Linear Algebra and Analytic Geometry',3);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Основи програмної інженерії / Fundamentals of Software Engineering',7.5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Українська мова (за професійним спрямуванням) / Ukrainian Language (for Special Purpose)',3);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Іноземна мова / Foreign Language',5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Фізика / Physics',4);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Безпека життєдіяльності / Health Safety',1.5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Об''єктно-орієнтоване програмування / Object-Oriented Programming',5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Проектний практикум / Design Practical Work',1.5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Фізичне виховання / Physical Training',8);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Алгоритми та структури даних / Algorithms and Data Structures',5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Архітектура та проектування програмного забезпечення / Software Architecture and Engineering',5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Комп''ютерна дискретна математика / Computer Discrete Mathematics',5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Бази даних / Databases',4);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Теорія ймовірності та математична статистика / Theory of Probability and Mathematical Statistics',3);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Групова динаміка і комунікації / Group Dynamics and Communications',2);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Мультимедіа-системи / Multimedia Systems',2);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Історія української культури / History of the Ukrainian Culture',2);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Операційні системи / Operating Systems',6);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Бази даних (частина II) / Databases (Part II)',4);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Основи крос-платформенного програмування / Fundamentals of Cross-platform Programming',3.5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Безпека програм та даних / Program and Data Security',3.5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Соціологія / Sociology',2);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Методи та засоби обробки знань в геології нафти і газу / Knowledge Processing Methods and Means in Oil and Gas Geology',8);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Аналіз вимог до програмного забезпечення / Analysis of Software Requirements',4);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Емпірічні методи програмної інженерії / Empirical Methods of Software Engineering',4);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Людино-машинний інтерфейс / Human-Computer Interface',3.5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Інтелектуальні системи аналізу даних / Data Analysis Intelligence Systems',4);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Політологія / Science of Politics',2);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Операційні системи UNIX / UNIX Operating Systems',3);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Методологічні основи наукових досліджень в нафтогазовій галузі / Methodological Fundamentals of Oil and Gas Branch Research',8);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Дискретні структури / Discrete Structures',3.5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Конструювання програмного забезпечення / Software Design',4);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Менеджмент проектів програмного забезпечення / Software Design Management',3);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Організація комп''ютерних мереж / Computer Network Organization',3);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Професійна практика програмної інженерії / Software Engineering Professional Practice',2.5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Якість програмного забезпечення та тестування / Software Quality and Testing',3.5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Правознавство / Law Science',2);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Моделювання програмного забезпечення / Software Modeling',5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Мови програмування для web / Web Computer Languages',5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Технології компонентного програмного забезпечення / Component Software Technologies',5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Економічна теорія / Economic Theory',2);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Паралельне програмування / Parallel Programming',6);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Архітектура комп''ютерів / Computer Architecture',5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Розробка web-застосувань / Web-Application Development',2);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Основи охорони праці / Fundamentals of Labour Protection',1.5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Математичне моделювання процесів розробки нафтогазових родовищ / Mathematical Modeling of Oil and Gas Field Processes',3);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Екологія / Ecology',1.5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Агентно-орієнтоване програмування / Agent-Oriented Programming',2);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Програмні системи для математичних розрахунків та моделей / Software Systems for Mathematical Calculations and Models',2);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (2, 'Об''єктно-орієнтоване програмування / Object-Oriented Programming',3);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (2, 'Бази даних / Databases',2);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (2, 'Інтелектуальні системи аналізу даних / Data Analysis Intelligence Systems',2);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (2, 'Технології компонентного програмного  забезпечення / Component Software Technologies',2.5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (3, 'Виробнича практика  / Field Internship',9);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (3, 'Переддипломна практика / Pre-Diploma Internship',6);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (4, 'Дипломна робота бакалавра / Bachelor’s Diploma Work',9);
