INSERT INTO diploma_subject (subject_uk, subject_en) VALUES
  ('Розробка інтелектуального рішення обробки даних з використанням асоціативних правил',
   'Development of the data processing intellectual solution using association rules'),
  ('Розробка програмного рішення ведення особистого блогу', 'Development of software solution for personal blogging'),
  ('Розробка веб-базованого програмного додатку онлайн запису до лікаря', 'Development of web based software application for online medical appointments'),
  ('Розробка WEB - додатку для автоматизованої роботи агентства з продажу та оренди квартир', 'Diploma subject #4'),
  ('Розробка мобільного програмного додатку онлайн запису до лікаря', 'Development of mobile software application for online medical appointments'),
  ('Тема Дипломної #6', 'Diploma subject #6'),
  ('Розробка прототипу експертної системи в предметній області', 'Development of prototype expert system in the subject area'),
  ('Розробка програмного рішення підтримки контенту та користувачів блогу', 'Development of software solution for the content and blog user support'),
  ('Розробка програмного продукту підтримки опитувань користувачів', 'Development of software product for the user survey support'),
  ('Розробка програмного продукту підтримки опитувань користувачів', 'Development of software product for the user survey support'),
  ('Тема Дипломної #11', 'Diploma subject #11'),
  ('Розробка інформаційно-довідкового WEB - сервісу для торгово-виробничого підприємства', 'Development of information reference web-based service for the commercial manufacturing enterprise'),
  ('Розробка веб-базованого онлайн  сервісу подання та оформлення візових документів', 'Development of web-based online service for submission and release of visa documents'),
  ('Розробка мобільного додатку шифрування даних', 'Development of mobile application for data encryption'),
  ('Розробка клієнт-серверного додатку органайзера з елементами 3D графіки', 'Development of the organizer client-server end application with 3D graphics elements'),
  ('Розробка WEB - орієнтованого додатку для обміну миттєвими повідомленнями в реальному часі', 'Development of web-based application for instant message exchange in real time'),
  ('Реалізація життєвого циклу контролю результатів навчання', 'Implementation of life cycle for the academic results control'),
  ('Реалізація основних функцій систем керування вмістом', 'Implementation of main functions of the content management systems'),
  ('Розробка он-лайн сервісу для розповсюдження авторського контенту засобами Spring', 'Development of online service for the copyrighted content distribution  using Spring tools'),
  ('Розробка WEB - орієнтованого сервісу для продажу електроніки', 'Development of web-based service for electronics sales'),
  ('Розробка системами управління даними санаторію', 'Development of web-based service for electronics sales'),
  ('Розробка програмного забезпечення формування замовлень товарів', 'Development of software for order placement'),
  ('Розробка WEB-базованого програмного забезпечення для покращення роботи готельного бізнесу', 'Development of web-based software for the hotel business improvement'),
  ('Розробка android - додатку для автоматизованої роботи агентства з продажу та оренди квартир', 'Development of Android application for automated environment of the apartment rental and sales agency'),
  ('Реалізація програмної структури типових стратегій електронної комерції', 'Implementation of software structure for the electronic commerce standard strategies'),
  ('Розробка веб-базованого сервісу для обміну фото роботами', 'Development of web-based service for photo sharing'),
  ('Розробка WEB-базованого сервісу для продажі спортивних товарів', 'Development of web-based service for the sports goods sale'),
  ('Розробка програмного забезпечення віртуалізації планування навчання', 'Development of software for the academic planning virtualization'),
  ('Розробка клієнт-сервісного застосунку для обліку грошових потоків міжміського транспорту', 'Development of client-service application for the intercity transport cash flow accounting'),
  ('Розробка Web - орієнтованої системи обліку навчального плану студента засобами РНР', 'Development of web-based system for the student academic curriculum management using PHP tools'),
  ('Розробка програмного рішення контролю віддалених ресурсів', 'Development of software product for library resources electronic cataloguing'),
  ('Розробка програмного забезпечення обробки клієнтських оцінок', 'Development of software for the client assessment”'),
  ('Розробка програмного забезпечення веб-сервісу з продажу обчислювальної техніки', 'Development of software for the computing equipment sales web servic'),
  ('Розробка налаштовуваного програмного рішення для текстового редактора', 'Development of configurable software solution for the text editor'),
  ('Реалізація типових клієнтських сервісів електронної комерції', 'Development of configurable software solution for the text editor'),
  ('Розробка алгоритмічного та програмного забезпечення Інтернет магазину косметичної компанії', 'Development of algorithm and software for the cosmetics company online shop'),
  ('Розробка програмного рішення підтримки груп розсилок', 'Development of software solution for the electronic mailing support'),
  ('Розробка обліково-пошукової системи студентської активності', 'Development of the student activity recording and search system'),
  ('Розробка інтерфейсу бази даних реалізації товарів та послуг', 'Development of database interface for vehicle parts sale'),
  ('Розробка програмного продукту візуалізації мережі', 'Development of the network visualization software product'),
  ('Програмна реалізація бази даних засобів цивільного захисту', 'Software implementation of the civil defence tools database'),
  ('Програмна реалізація бази даних засобів цивільного захисту', 'Software implementation of the civil defence tools database'),
  ('Розробка інформаційного порталу кінотеатру', 'Development of the cinema information portal'),
  ('Розробка програмного прототипу системи автоматизації закладу медичного обслуговування', 'Development of software for the prototype automation system of the medical service facilities'),
  ('Розробка програмного рішення для служби тилу військових з''єднань', 'Development of software solution for the support service of military units'),
  ('Реалізація програмного сервісу телекомунікаційної стратегії', 'Development of software solution for the support service of military units'),
  ('Розробка веб-орієнтованої системи візуалізації діяльності будівельної компанії', 'Development of web-based visualization system for the construction company activities'),
  ('Реалізація процесів підтримки прийняття рішень в бухгалтерському обліку', 'Implementation of the decision support processes in accounting'),
  ('Розробка програмного рішення оптимізації використання сировини', 'Development of software solution for the raw material use optimization'),
  ('Розробка програмного рішення бази даних системного адміністратора', 'Development of software solution for the system administrator’s database'),
  ('Програмна реалізація засобів графічних інтерфейсів для тестування знань', 'Software implementation of graphical interface tools for knowledge testing'),
  ('Розробка програмного рішення доставки вантажів', 'Development of software solution for cargo delivery'),
  ('Розробка програмного продукту автоматичної генерації додатків європейського взірця для студентів, що навчаються за ступенем вищої освіти “магістр”', 'Development of software product for automatic generation of the diploma supplements of European Standard for Master Students'),
  ('Розробка інтерфейсу бази даних реалізації автомобільних запчастин', 'Development of database interface for vehicle parts sale'),
  ('Дослідження протоколу HTTP та розробка програмного забезпечення web-сервера', 'Study of HTTP protocol and development of web-server software'),
  ('Розробка експертного програмного рішення контролю мережевого оточення', 'Development of expert software solution for network environment control'),
  ('Розробка мобільного додатку для відображення розкладу студентів у середовищі IOS', 'Development of mobile application for student’s course schedule in IOS environment'),
  ('Розробка серверної частини інформаційної системи замовлення їжі та продуктів', 'Development of food delivery information system server end'),
  ('Розробка серверної частини та модуля обробки даних програмного продукту для відділу HR в ІТ компаніях', 'Development of the software product server end and data processing module for HR Department in IT companies'),
  ('Розробка серверної навчального середовища використання нейромереж для задач класифікації та кластеризації засобами .NET', 'Development of the neural net use learning environment server end for classification and clustering tasks using .NET tools'),
  ('Розробка хмарного сервісу обміну документами', 'Development of the document exchange cloud-based service'),
  ('Розробка програмного забезпечення обліку присутності студентів', 'Development of software for records of student attendance'),
  ('Програмна реалізація задачі масового обслуговування на прикладі вантажоперевезень', 'Software realization of the public service tasks by the cargo transportation example'),
  ('Розробка прототипу веб-системи студентського файлового обмінника', 'Development of prototype web-system of the student file sharing tool'),
  ('Розробка клієнтської частини навчального середовища використання нейромереж для задач класифікації та кластеризації засобами .NET', 'Development of the neural net use learning environment client end for classification and clustering tasks using .NET tools'),
  ('Розробка програмного продукту автоматичної генерації додатків європейського взірця для студентів, що навчаються за ступенем вищої освіти “бакалавр”»', 'Development of software product for automatic generation of the diploma supplements of European Standard for Bachelor Students'),
  ('Розробка програмного рішення автоматизації роботи діяльності підприємства', 'Development of software solution for the enterprise activities automation'),
  ('Розробка програмного продукту аналізу і контролю маркетингової діяльності підприємства', 'Development of software product for the enterprise marketing activity analysis and control'),
  ('Розробка клієнтської частини інформаційної системи замовлення їжі та продуктів', 'Development of food delivery information system client end'),
  ('Розробка клієнтської частини веб-системи інформаційної підтримки соціальних ініціатив громадських активістів міста', 'Development of web-based information management system client end for social initiatives of the community activists'),
  ('Розробка WEB - орієнтованої онлайн карткової стратегії', 'Development of web-based online card strategy'),
  ('Розробка серверної частини веб-системи інформаційної підтримки соціальних ініціатив громадських активістів міста', 'Development of web-based information management system server end for social initiatives of the community activists'),
  ('Тема Дипломної #73', 'Diploma subject #73'),
  ('Розробка програмного продукту менеджменту проектів для працівників ІТ компаній', 'Development of project management software product for IT company personnel'),
  ('Розробка двигуна та механіки ігрового мобільного додатку типу аркада', 'Development of the arcade game mobile application engine and mechanics'),
  ('Розробка Інформаційної системи контролю та управління доступу відвідувачів засобами asp.net core', 'Development of access control and management information system for visitors using asp.net core tools'),
  ('Розробка моделей веб-орієнтованих програмних сервісів', 'Development of the software service web-based models'),
  ('Розробка дизайну та інтерфейсу ігрового мобільного додатку типу аркада', 'Development of the arcade game mobile application engine and mechanics'),
  ('Програмна реалізація транспортних задач маршрутизації', 'Software implementation of the routing transport tasks'),
  ('Розробка web-орієнтованого програмного забезпечення для продажу автомобілів', 'Development of web-based software for car sales'),
  ('Розробка програмного продукту електронної каталогізації бібліотечних ресурсів', 'Development of software product for library resources electronic cataloguing'),
  ('Розробка мобільного додатку для відображення розкладу студентів у середовищі Android',
   'Development of mobile application for student’s course schedule in Android environment'),
  ('Розробка програмного забезпечення діагностики транспортних засобів',
   'Development of mobile application for student’s course schedule in Android environment'),
  ('Розробка клієнтської частини програмного продукту для відділу HR в ІТ компаніях',
   'Development of the software product client end and data processing module for HR Department in IT companies'),
  ('Програмна реалізація локалізованого пошукового засобу', 'Software implementation of the localized search tool'),
  ('Інформаційні моделі програмних засобів структурного програмування',
   'Information models of the structural programming software tools'),
  ('Розробка програмного забезпечення ведення бази даних клієнтів автосервісу',
   'Information models of the structural programming software tools'),
  ('Розробка програмного рішення робочого місця провізора',
   'Development of software solution for the pharmacist’s workplace'),
  ('Розробка програмного забезпечення прототипу файлового менеджера',
   'Development of software for the file manager prototype support');