INSERT INTO diploma_subject (subject_uk, subject_en) VALUES
  ('Моделі, методи та алгоритми застосувань результатів імітаційного моделювання',
   'Models, methods and algorithms for applying simulation study results'),
  ('Моделі, методи та алгоритми механізмів роботи пошукових систем',
   'Мodels, methods and algorithms of search systems operating principles'),
  ('Моделі, методи та алгоритми смарт-евристик процесу фрагментації в базах даних',
   'Models,  methods and algorithms of smart heuristics of the fragmentation process in databases'),
  ('Моделі, методи та алгоритми гібридизації нечітких даних в структурах проектів',
   'Models, methods and algorithms for fuzzy data hybridization in project structures'),
  ('Моделі, методи та алгоритми для обробки даних та організації роботи онлайн путівника',
   'Models, methods and algorithms for processing and organizing the On-line Guide work'),
  ('Моделі, методи та алгоритми процесів інференції даних геологічних досліджень',
   'Models, methods and algorithms of data interference processes of geological studies'),
  ('Моделі та методи роботи алгоритмів шифрування невеликих масивів даних',
   'Models, methods of algorithms’s work  of encryption of small data sets'),
  ('Моделі та методи застосування нейромереж при роботі з великими даними',
   'Models and methods of using neuronet while working  with big data'),
  ('Моделі, методи та алгоритми побудови навчальних систем на основі імітаційного моделювання',
   'Мodels, methods and algorithms of building educational systems based on simulation modeling'),
  ('Моделі, методи та алгоритми автоматизації систем управління в сфері логістики',
   'Models, methods and algorithms of automation of management systems in the field of logistics'),
  ('Моделі, методи та алгоритми знання-орієнтованих інформаційних мереж',
   'Models, methods and algorithms of knowledge-oriented information networks'),
  ('Моделі та методи застосування генетичних алгоритмів при роботі з великими даними',
   'Models and methods of applying genetic algorithms while working with big data'),
  ('Моделі, методи та алгоритми функціонування блокчейну',
   'Models, methods and algorithms of blockchain functioning'),
  ('Методи та алгоритми інформаційних моделей систем захисту інформації',
   'Мethods and algorithms of information models of data protection systems'),
  ('Моделі, методи та алгоритми зважування та оцінки інвестиційних проектів',
   'Models, methods and algorithms for deliberating and evaluating investment projects'),
  ('Методи та алгоритми адаптивних моделей систем тестування',
   'Methods and algorithms of adaptive models of testing systems'),
  ('Моделі, методи та алгоритми комплексного управління закладом вищої освіти',
   'Models, methods and algorithms of complex management of higher education institution'),
  ('Моделі, методи та алгоритми параметричної ідентифікації складних об''єктів',
   'Models, methods and algorithms for parametric identification of complex objects'),
  ('Моделі, методи та алгоритми інтерактивної навчальної мультимедіа',
   'Models, methods and algorithms of interactive educational multimedia'),
  ('Моделі, методи та алгоритми програмної підтримки соціальних ініціатив',
   'Models, methods and algorithms for social initiatives software support'),
  ('Моделі, методи та алгоритми розподілу преференцій авторизації та автентифікації',
   'Models, methods and algorithms for the distribution of preferences for authorization and authentication'),
  ('Моделі, методи та алгоритми імплементації штучних інтелектуальних сутностей в мережевому середовищі',
   'Models, methods and algorithms for the implementation of artificial intellectual entities in a network environment'),
  ('Моделі, методи та алгоритми структуризації систем оцінки результатів тестування',
   'Models, methods and algorithms for structuring systems of test results evaluation'),
  ('Моделі, методи та алгоритми організації обробки даних в системах документообігу міських установ',
   'Models, methods and algorithms for organizing data processing in workflow systems of municipal institutions'),
  ('Моделі, методи та алгоритми штучного інтелекту в процесі управління',
   'Models, methods and algorithms of artificial intelligence in the management process'),
  ('Моделі, методи та алгоритми ієрархічного планування ресурсів з накладеними обмеженнями',
   'Models, methods, and algorithms for hierarchical planning of resources with imposed restrictions'),
  ('Моделі, методи та алгоритми для обробки даних цифрової фотографії',
   'Models, methods and algorithms for processing digital photo data'),
  ('Моделі, методи та алгоритми керування якістю програмних продуктів в динаміці життєвого циклу',
   'Models, methods and algorithms of software quality management in life cycle dynamics'),
  ('Моделі, методи та алгоритми процесу оцінки цінності землі в залежності від географії місця розташування',
   'Models, methods and algorithms of the land valuation process, depending on the geography of the location'),
  ('Моделі, методи та алгоритми оптимізації об''ємів документообігу',
   'Models, methods and algorithms for optimizing workflow volumes'),
  ('Моделі, методи та алгоритми застосування експертних систем в освітній галузі',
   'Models, methods and algorithms for the use of expert systems in education'),
  ('Моделі, методи та алгоритми автоматизації операцій на біржі',
   'Models, methods and algorithms for automation of stock exchange operations'),
  ('Моделі, методи та алгоритми балансування та розподілу інформаційного забезпечення',
   'Models, methods and algorithms for balancing and distribution of information support'),
  ('Моделі, методи та алгоритми сервіс-орієнтованих систем в Інтернет медіа сфері',
   'Models, methods and algorithms of service-oriented systems in the Internet media sphere'),
  ('Моделі, методи та алгоритми уніфікації освітньо-мережевого простору',
   'Models, methods and algorithms for unification of the educational network space'),
  ('Моделі, методи та алгоритми реалізації систем підтримки прийняття рішень у харчовій галузі',
   'Models, methods and algorithms for implementing decision-making support systems in the food industry'),
  ('Моделі, методи та алгоритми реалізації запитів по даних в умовах невизначеності',
   'Models, methods and algorithms for querying data under uncertainty'),
  ('Моделі, методи та алгоритми реалізації зворотного зв''язку в навчальних системах',
   'Models, methods and algorithms for the feedback in educational systems'),
  ('Моделі, методи та алгоритми застосування штучного інтелекту для виявлення мережевих загроз',
   'Models, methods, and algorithms for using artificial intelligence to identify threats to network'),
  ('Моделі, методи та алгоритми оптимізації машинного навчання',
   'Machine learning optimization models, methods and algorithms'),
  ('Моделі, методи та алгоритми інформаційного забезпечення HR-відділів ІТ компаній',
   'Models, methods and algorithms for information support of IT companies HR-departments');