INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Охорона праці в галузі / Labour Safety in Field',4);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Архітектура програмного забезпечення / Software Architecture ',5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Моделювання ІТ інновацій / IT Innovations Modeling',6);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Інноваційні підходи створення ІТ проектів / Innovative Approaches to IT Project Development ',4);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Проектування сховищ даних / Data Warehouse Design',5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Інженерія вимог / Requirements Engineering',5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Розроблення web-додатків в розподілених системах / Development of Web-Based Applications in Distributed Systems',3);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Системологія інженерії програмного забезпечення / Software Engineering Systemology',4);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Спецкурс керівника / Manager’s Special Course',4);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Формальні методи програмної інженерії / Formal Methods of Software Engineering',5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Педагогіка вищої школи / Higher Education Pedagogics',3);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Філософські проблеми наукового пізнання / Philosophical Problems of Scientific Cognition',3);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Логічний аналіз / Logic Analysis',5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Системи на основі знань / Knowledge-based systems',3);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Методологія та методи наукових досліджень / The methodology and methods of scientific researches',3.5);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (1, 'Моделювання процесів розробки програмного забезпечення / Modeling of Software Development Processes',4);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (2, 'Моделювання ІТ інновацій / IT Innovations Modeling',1);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (3, 'Науково-дослідна практика / Research Practical Training',9);
INSERT INTO educational_component_template(educational_component_type_id, course_title, credits) VALUES (4, 'Магістерська робота / Master’s Thesis',13.5);